# 1.0 简介

numpy是python机器学习技术栈的基础，能高效操作向量，矩阵和张量

# 1.1 创建一个向量

In [5]:
# 加载库
import numpy as np

# 创建一个行向量
vector_row = np.array([1, 2, 3])

# 创建一个列向量
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_row

array([1, 2, 3])

In [6]:
vector_column

array([[1],
       [2],
       [3]])

# 1.2创建一个矩阵

In [8]:
# 创建一个矩阵
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

# NumPy也提供专用的矩阵对象（但不推荐）
matrix_object = np.asmatrix([[1, 2],
                            [1, 2],
                            [1, 2]])

In [9]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [10]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

# 1.3创建一个稀疏矩阵

高效地表示只有零星非零值的数据

In [11]:
# 加载库
import numpy as np
from scipy import sparse

# 创建一个矩阵
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# 创建一个压缩的稀疏行（CSR）矩阵
matrix_sparse = sparse.csr_matrix(matrix)

In [12]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [13]:
matrix_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

查看稀疏矩阵

In [14]:
print(matrix_sparse)  # 只显示非零元素的位置和值
# 输出：
# (1, 1)  1
# (2, 0)  3

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


稀疏矩阵的优势

In [15]:
# 创建一个更大的矩阵
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)
# 表示方式与小的稀疏矩阵相同

In [16]:
matrix_large

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
matrix_large_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>

# 1.4 选择元素

In [20]:
# 创建一个行向量
vector = np.array([1, 2, 3, 4, 5, 6])

# 创建矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 选择向量的第三个元素
vector[2]  # 输出: 3

np.int64(3)

In [19]:
# 选择第二行第二列
matrix[1, 1]  # 输出: 5

np.int64(5)

索引和切片操作

In [21]:
# 选取一个向量的所有元素
vector[:]  # array([1, 2, 3, 4, 5, 6])

# 选取从0开始一直到第3个（包括第3个）元素
vector[:3]  # array([1, 2, 3])

# 选取第3个元素之后的所有元素
vector[3:]  # array([4, 5, 6])

# 选取最后一个元素
vector[-1]  # 6

# 选取矩阵的第1行和第2行以及所有列
matrix[:2, :]  # array([[1, 2, 3], [4, 5, 6]])

# 选取所有行以及第二列
matrix[:, 1:2]  # array([[2], [5], [8]])

array([[2],
       [5],
       [8]])

# 1.5展示一个矩阵的属性

展示一个矩阵的大小维度形状

In [25]:
# 创建矩阵
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# 查看行数和列数
matrix.shape  # (3, 4)

(3, 4)

In [23]:
# 查看元素的数量（行数×列数）
matrix.size  # 12

12

In [24]:
# 查看维数
matrix.ndim  # 2

2

# 1.6 对多个元素同时应用某个操作

对一个数组中的多个元素同时应用某个函数

In [26]:
# 加载库
import numpy as np

# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 创建一个函数，返回输入值加上100以后的值
add_100 = lambda i: i + 100

# 创建向量化函数
vectorized_add_100 = np.vectorize(add_100)

# 应用向量化函数
vectorized_add_100(matrix)
# 输出:
# array([[101, 102, 103],
#        [104, 105, 106],
#        [107, 108, 109]])

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

numpy的广播机制

In [27]:
# 将所有的元素加上100
matrix + 100
# 输出同上

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# 1.7 找到最大值和最小值

计算一个数组的最大值和最小值

In [30]:
# 加载库
import numpy as np

# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 返回最大的元素
np.max(matrix)  # 9

np.int64(9)

In [29]:
# 返回最小的元素
np.min(matrix)  # 1

np.int64(1)

按轴操作

In [31]:
# 找到每一列最大的元素
np.max(matrix, axis=0)  # array([7, 8, 9])

# 找到每一行最大的元素
np.max(matrix, axis=1)  # array([3, 6, 9])

array([3, 6, 9])

# 1.8计算平均值方差和标准差

计算数组的一些描述性统计量

In [35]:
# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 返回平均值
np.mean(matrix)  # 5.0

np.float64(5.0)

In [36]:

# 返回方差
np.var(matrix)   # 6.666666666666667

np.float64(6.666666666666667)

In [37]:
# 返回标准差
np.std(matrix)   # 2.5819888974716112

np.float64(2.581988897471611)

按轴计算

In [38]:
# 求每一列的平均值
np.mean(matrix, axis=0)  # array([4., 5., 6.])

array([4., 5., 6.])

# 1.9 矩阵变形

在不改变元素值的前提下，改变一个数组的形状（行数和列数）

In [39]:
# 创建一个4×3的矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# 将该矩阵变形为2×6的矩阵
matrix.reshape(2, 6)
# 输出:
# array([[ 1,  2,  3,  4,  5,  6],
#        [ 7,  8,  9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

讨论

reshape要求原矩阵和新矩阵包含的元素数量必须相同
可使用size查看矩阵大小：matrix.size  # 12
参数-1表示"根据需要填充元素"：matrix.reshape(1, -1) 或 matrix.reshape(-1, 1)
只提供一个整数参数会返回一维数组：matrix.reshape(12)

# 1.10 转置向量或矩阵

转置一个向量或者矩阵

In [40]:
# 加载库
import numpy as np

# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 转置一个矩阵
matrix.T
# 输出:
# array([[1, 4, 7],
#        [2, 5, 8],
#        [3, 6, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

转置一个向量

In [41]:
# 将向量转置（无效果）
np.array([1, 2, 3, 4, 5, 6]).T  # 返回原数组

# 转置一个行向量（需先转为二维）
np.array([[1, 2, 3, 4, 5, 6]]).T
# 输出列向量

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 1.11 展开一个矩阵

将矩阵转换为一个一维数组

In [42]:
# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 将矩阵展开
matrix.flatten()  # array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

替代方法

In [43]:
# 使用reshape创建行向量
matrix.reshape(1, -1)  # array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 1.12 计算矩阵的秩

In [44]:
# 创建一个矩阵
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# 返回矩阵的秩
np.linalg.matrix_rank(matrix)

np.int64(2)

讨论：矩阵的秩是由它的列或行展开的向量空间的维数。


# 1.13 计算行列式

计算一个矩阵的行列式

In [45]:
# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 返回矩阵的行列式
np.linalg.det(matrix)  # 0.0

np.float64(0.0)

行列式为0表示矩阵是奇异的（不可逆）。

# 1.14 获取矩阵的对角线元素

In [46]:
# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 返回对角线元素
matrix.diagonal()  # array([1, 4, 9])

array([1, 4, 9])

In [47]:
# 返回主对角线向上偏移量为1的对角线元素
matrix.diagonal(offset=1)  # array([2, 6])

# 返回主对角线向下偏移量为1的对角线元素
matrix.diagonal(offset=-1)  # array([2, 8])

array([2, 8])

# 1.15 计算矩阵的迹

In [48]:
# 创建一个矩阵
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 返回矩阵的迹
matrix.trace()  # 14

np.int64(14)

代替方案

In [49]:
# 返回对角线元素并求和
sum(matrix.diagonal())  # 14

np.int64(14)

# 1.16 计算特征值和特征向量

In [50]:
# 创建一个矩阵
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# 查看特征值
eigenvalues
# 输出: array([13.55075847,  0.74003145, -3.29078992])

# 查看特征向量
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

讨论：特征向量在机器学习库中被广泛使用。对于线性变换矩阵A，特征向量只改变大小不改变方向，满足 Aν = λν。

# 1.17 计算点积

In [51]:
# 创建两个向量
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# 计算点积
np.dot(vector_a, vector_b)  # 32

# Python 3.5+ 使用 @ 操作符
vector_a @ vector_b  # 32

np.int64(32)

# 1.18 矩阵的相加和相减

In [52]:
# 创建两个矩阵
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# 将两个矩阵相加
np.add(matrix_a, matrix_b)
# array([[ 2,  4,  2],
#        [ 2,  4,  2],
#        [ 2,  4, 10]])

# 将两个矩阵相减
np.subtract(matrix_a, matrix_b)
# array([[ 0, -2,  0],
#        [ 0, -2,  0],
#        [ 0, -2, -6]])

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

简化操作

In [54]:
# 使用 + 和 - 操作符
matrix_a + matrix_b


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [55]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# 1.19 矩阵的乘法

In [58]:
# 创建两个矩阵
matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

# 将两个矩阵相乘
np.dot(matrix_a, matrix_b)
# array([[2, 5],
#        [3, 7]])


array([[2, 5],
       [3, 7]])

In [59]:

# Python 3.5+ 使用 @ 操作符
matrix_a @ matrix_b


array([[2, 5],
       [3, 7]])

In [60]:
# 对应元素相乘（Hadamard积）
matrix_a * matrix_b
# array([[1, 3],
#        [1, 4]])

array([[1, 3],
       [1, 4]])

# 1.20计算矩阵的逆

In [61]:
# 创建一个矩阵
matrix = np.array([[1, 4],
                   [2, 5]])

# 计算逆矩阵
np.linalg.inv(matrix)
# array([[-1.66666667,  1.33333333],
#        [ 0.66666667, -0.33333333]])

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

验证

In [62]:
# 将矩阵和它的逆矩阵相乘得到单位矩阵
matrix @ np.linalg.inv(matrix)
# array([[1., 0.],
#        [0., 1.]])

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

# 1.21 生成随机数

In [63]:
# 加载库
import numpy as np
# 设置随机数种子（保证可重复性）
np.random.seed(0)

array([1.47997717, 1.3927848 , 1.83607876])

In [65]:
# 生成3个0到1之间的随机浮点数
np.random.random(3)

array([0.10590761, 0.47360042, 0.18633234])

In [67]:

# 生成3个1到10之间的随机整数
np.random.randint(0, 11, 3)  # array([3, 7, 9])

array([9, 3, 6], dtype=int32)

In [70]:
# 从正态分布中抽取3个数（均值0.0，标准差1.0）
np.random.normal(0.0, 1.0, 3)


array([-0.63972264, -0.4794198 ,  0.3113635 ])

In [71]:
# 从logistic分布中抽取3个数
np.random.logistic(0.0, 1.0, 3)

array([-1.83046447, -1.40779319, -0.53768974])

In [72]:

# 从均匀分布中抽取3个数（范围[1.0, 2.0)）
np.random.uniform(1.0, 2.0, 3)

array([1.82099323, 1.09710128, 1.83794491])

# 知识点总结

知识点总结
核心概念：
NumPy基础：机器学习技术栈的基础库，核心数据结构是ndarray
向量化操作：避免显式循环，利用广播机制进行高效计算
轴（axis）：axis=0表示列操作，axis=1表示行操作
稀疏矩阵：只存储非零元素，大幅节省内存
索引与切片：从0开始，支持负索引和多种切片方式
常用函数分类：
创建与变形：
np.array() - 创建数组
reshape() - 改变形状
.T - 转置
flatten() - 展平
属性查询：
.shape - 形状
.size - 元素总数
.ndim - 维数
数学运算：
np.dot() / @ - 点积/矩阵乘法
np.add() / + - 加法
np.subtract() / - - 减法
* - 元素级乘法（Hadamard积）
统计计算：
np.max() / np.min() - 最值
np.mean() - 平均值
np.var() - 方差
np.std() - 标准差
线性代数：
np.linalg.matrix_rank() - 矩阵的秩
np.linalg.det() - 行列式
np.linalg.eig() - 特征值和特征向量
np.linalg.inv() - 逆矩阵
.trace() - 迹
.diagonal() - 对角线元素
随机数生成：
np.random.seed() - 设置随机种子
np.random.random() - 均匀分布[0,1)
np.random.randint() - 随机整数
np.random.normal() - 正态分布
np.random.uniform() - 均匀分布